### ISSUE TITLE
Version Requirements for Dogelog Player

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [hurufu/prolog-all#3]
I was doing a little research, different versions of
Java usually adopt "java" as the command line for
the bytecode interpreter and JIT compiler.

Maybe thats why the arch linux packages shows a lot
of different Java systems. But in fact it must be
above version 21, otherwise it doesn't run.

It is particular tested with Oracle Java and GraalVM Java,
version 23, but version 21 would also do at the moment.

But now have at least "node" and "bun" for JavaScript,
and as well at least "pypy3" and "python3" for Python.
But the arch packages show dependencies to

"python3" and "node". But in fact this is again not
extremly hard wired for Dogelog Player. In fact "pypy3"
is recommended over "python3", since its faster.

For "bun" versus "node" I don't know yet, one has to
observe the situation. Version wise also certain older
versions don't work. Maybe I should publish the

version requirements somewhere. But its hard to judge
sometimes. You can do this check to see whether your
versions that you have on your system are compatible:

mkdir xlog
cd xlog
git clone https://www.dogelog.ch/dogelog/.git
git clone https://www.novacuor.ch/novacore/.git
cd novacore
ant -f harness/run.xml
webfsd -p 8598

Look at the test results via:

http://localhost:8598/

**Comment by Jean-Luc-Picard-2021** [comment]
Whats also extremly annonying. A very early version
of node 23.x didn't work correctly. So I fell back
to node 22.x. Still waiting to do some retest with 23.x.

What worked for me in the tip release is actually published here:
```
j    Dogelog Player 1.2.5, Java 23.0.1
js    Dogelog Player 1.2.5, JavaScript 22.11.0
py    Dogelog Player 1.2.5, Python 3.10.14
```
https://www.novacuor.ch/exatab/doclet/docs/10_core/ryzen/package.html?hash=bench

But Python is in fact PyPy and JavaScript is curently node.
But the above doesn't reflect really the minimum, rather
only the known maximum on Windows 11.

**Comment by hurufu** [comment]
Thanks, for that remark, I will create a fixed list of supported java versions.

**Comment by hurufu** [comment]
I will do it probably later today or tomorrow. I'll keep you informed.

**Comment by Jean-Luc-Picard-2021** [comment]
Concerning Java, most people will notice since dogelog.zip
is compiled with Class File Version 65.0 which belongs to JDK 21:

![393534984-78badbfd-1634-41ee-b764-39b96753b58f](https://github.com/user-attachments/assets/fb2b79cf-365e-4bed-83f7-a1b76b8cdae3)
https://javaalmanac.io/bytecode/versions/

But the source code cannot compile as well, since it might use
some classes like [Sequenced Collections](https://openjdk.org/jeps/431) which were only introduced
in JDK 21. Inside these different JDK versions there is not

anymore some backward compatibility. And there are some 
interesting features around, like the HTTP client and Virtual Threads,
which are only available in higher versions. Similar situation with

node, fetch() is only available in higher versions. I hope I find a way
to document this better. Working on it.

**Comment by hurufu** [comment]
Done, but there is a lot to say.

### Java
I have fixed this for Java, so now it requires java-runtime ≥ 21 which is provided by both OpenJDK and GraalVM. Users are free to choose any runtime, but they still will need to run `sudo archlinux-java set java-23-openjdk` or something similar prior running Dogelog to set Java version system-wide and I expect users to know that. Website didn't change though it still lists *all* Java runtimes... I think it is a bug. Because after installation I have correct package description:
```
Name            : dogelog-java
Version         : 1.2.5-2
Description     : The avant-garde of logic programming (Java backend)
Architecture    : any
URL             : https://www.dogelog.ch/
Licenses        : custom
Groups          : None
Provides        : None
Depends On      : java-runtime>=21
Optional Deps   : None
Required By     : None
Optional For    : prologs
Conflicts With  : None
Replaces        : None
Installed Size  : 179.73 KiB
Build Date      : Sun Dec 8 10:59:32 2024
Install Date    : Sun Dec 8 11:01:17 2024
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

### JavaScript
JavaScript is different. Probably I will need to contact maintainers of `bun`, `bun-bin`, `bun-git`, `nodejs` and other maintainers to agree on a common `provides` field for all different JS runtimes (similar to `java-runtime`) something like `javascript-runtime` so then I can just use a single dependency. Other thing is that package is called dogelog-**node** which is unfortunate, because it implies that only node.js backend is supported a better name would've been `dogelog-js`. I will change the name, but I need to think how to deal with migration properly (I will need to add a `conflicts=(dogelog-node)` and some message would be useful too).

### Python
With Python there is a similar situation. Packages `python3` and `pypy3` don't have a common `provides` attribute and Python users use virtual environments. The only way I found is to set all engines as an "optional dependency". Also I have only fixed `python3` version, because pypy project claims to support only 3.10.x so any version will be Ok.


### P.S.

Someone already had similar concerns: https://bbs.archlinux.org/viewtopic.php?id=240307

Also, I did some tests on my laptop with different java variants, bun.js and pypy3 and they all seemed to work Ok.

### P.P.S.

I think I can write a script to test the actual minimum required version of different backends (just try all of them from arch linux packages archive), but I don't know when it will happen. Also it goes against the ethos of Arch Linux users, usually those people like to install "latest and greatest" software which is in contrast for example with Debian users which commonly prefer older by stable software.

**Comment by Jean-Luc-Picard-2021** [comment]
Ok, I like the pitch "latest and greatest". But what if there
are multiple maxima. If there is not a single latest and greatest,
or if it is a little diffuse. I think there is a similar situation when

choosing C compilers. There are also a variety of C compilers around:

https://wiki.archlinux.org/title/C#Alternative_compilers

I don't know how packagers resolve this dilemma. Or how it
is resolved in particular in the Arch Linux world. My GIT repositories
and ZIP distributions are totally agnostic. The only

choice that is made is inside `envir.xml`, if you download the 
Novecore test cases it will copy this template:
```
    <!-- Programming Language Platforms -->
    <property name="nodejs" location="/usr/bin/node"/>
    <property name="pypy3" location="/usr/bin/pypy3"/>
    <property name="jdk9" location="/usr/bin/java"/>
```
The template is copied into `harness/` when you [run the
test cases](https://www.xlog.ch/izytab/doclet/docs/06_start/03_novacore.html). You can manually edit envir.xml there and 
change it. But the template doesn't show the minimal versions,

only some common command line. To see the template do:
```
git clone https://www.novacuor.ch/novacore/.git
cd novacore
cat harness/template/envir.xml
```

**Comment by hurufu** [comment]
Generally it is a problem without solution, every program has its own convention or lack of thereof (like `CC` environment variable to select C compiler). It is somewhat solved problem for Java where /usr/bin/java is a symbolic link, but the configuration is global, and there is no ideal way to run different programs using different Java runtime (you can always set `JAVA_HOME`, and write wrapper scripts, but as I said it isn't ideal).

For Python most people just gave up on packaging and use virtual envs per project.

P.S. I should probably automate unit tests during package creation it would be nice to check if environment is sane, without me manually checking.

**Comment by Jean-Luc-Picard-2021** [comment]
I nearly discontinued Dogelog Player for Python, since it runs 
utterly slow on CPython. The only thing that keeps Dogelog Player
for Python alive is PyPy. Otherwise it would be dead.

The novacore test cases include compliance and benchmarking. The
benchmarking shows that Dogelog Player is practically impossible
to run under CPython. CPython is simply too slow.

On the other hand PyPy is feasible. PyPy is the recommended Python
for Dogelog Player. CPython is an alternative Python for Dogelog Player,
but it is not recommended at all. 

Can you get PyPy for Arch Unix, and place a PyPy dependency?
Here are some benchmark results showing CPython is horribly slow:

![image](https://github.com/user-attachments/assets/a9d31085-ed56-4c5f-be1e-4faaafb251ad)

Maybe its a problem with the memory setting. But I never investigate
CPython, I always develop against PyPy.

**Comment by hurufu** [comment]
Yes, pypy3 is already an optional dependency for dogelog-py: https://aur.archlinux.org/packages/dogelog-py. I just don't know how to make it a "recommended" dependency, because it isn't supported by the package manager. If you wish I can remove CPython dependency completely and make pypy as the only required dependency.

**Comment by Jean-Luc-Picard-2021** [comment]
I will push a new version of Novacore and Dogelog, which
includes CPython testing, in `main_alt`. Novacore test cases come
also in two flavors ZIP and GIT:

> **Directory "archive_1_0"**
https://www.novacuor.ch/srctab/doclet/en/docs/20_archive/archive_1_0/package.html

Some changes to Dogelog include that it can now show the 
platform in its flag `host_info`, which is used in the generated reports.
It is seen in the screenshot of my previous comment.

The previous screenshot above  also shows that 
CPython is ca. **25-times slower** than PyPy (sic!). And
I am already testing version 3.14.x of CPython.

**Comment by Jean-Luc-Picard-2021** [comment]
I have a lot of trust in PyPy. The next release and 
it will be faster than JavaScript node. Take my word!

P.S.: Carl Friedrich Bolz impressed me 20 years
ago or so, when he was handing me his prolog
for some testing, Pyrolog:

> **A Prolog Interpreter in Python**
https://cfbolz.de/Bolz2007-Bachelorarbeit.pdf

But they had also another Prolog systems
with Attribute Variables. But I don't anymore 
find a link yet to the other Prolog system

**Comment by Jean-Luc-Picard-2021** [comment]
Ok you wrote, so closing this ticket:

> Current version requirements for arch package are:
> 
> py CPython ≥ 3.10.14 or pypy3 (any version)
> js nodejs ≥ 22.11.0 or bun (any version)
> j  java-runtime ≥ 21
> 
> I expect users to apply common sense when trying to run Dogelog it should
> be obvious that very old interpreters might not work :)
